spring:
  datasource:
    url: ${SPRING_DATASOURCE_URL}
    driver-class-name: org.mariadb.jdbc.Driver
    username: ${SPRING_DATASOURCE_USERNAME}
    password: ${SPRING_DATASOURCE_PASSWORD}
  jpa:
    hibernate:
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
      dialect: org.hibernate.dialect.MariaDBDialect
      ddl-auto: none
    show-sql: true
    defer-datasource-initialization: true
  cloud:
    aws:
      s3:
        bucket: ${S3_BUCKET_NAME}
      credentials:
        access-key: ${CLOUD_AWS_ACCESS_KEY}
        secret-key: ${CLOUD_AWS_SECRET_KEY}
      region:
        static: ap-northeast-2
      stack:
        auto: false

jwt:
  secret: ${JWT_SECRET}