spring:
  datasource:
    url: ${SPRING_DATASOURCE_URL}
    driver-class-name: org.mariadb.jdbc.Driver
    username: ${SPRING_DATASOURCE_USERNAME}
    password: ${SPRING_DATASOURCE_PASSWORD}
  redis:
    host: ${SPRING_REDIS_HOST}
    port: ${SPRING_REDIS_PORT}
  jpa:
    hibernate:
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
      dialect: org.hibernate.dialect.MariaDBDialect
      ddl-auto: validate
    properties:
      hibernate:
        show_sql: true
        format_sql: true
        use_sql_comments: true
cloud:
  aws:
    credentials:
      access-key: ${CLOUD_AWS_ACCESS_KEY}
      secret-key: ${CLOUD_AWS_SECRET_KEY}
    s3:
      bucket: ${S3_BUCKET_NAME}
      region: ap-northeast-2
    ses:
      mail-address: ${SES_MAIL_ADDRESS}
      region: ap-northeast-1

encryption:
  spec: ${ENCRYPTION_SPEC}
  secret: ${ENCRYPTION_SECRET}
  algorithm: ${ENCRYPTION_ALGORITHM}

jwt:
  secret: ${JWT_SECRET}

exceed:
  url : https://eatceed.net
  deepLink : eatceed://deeplink

springdoc:
  api-docs:
    path: /api-docs # API 문서 생성 경로
    groups:
      enabled: true
  swagger-ui:
    path: /index.html # Swagger-ui 경로
    enabled: true
    groups-order: asc
    tags-sorter: alpha
    operations-sorter: alpha
    display-request-duration: true
    doc-expansion: none
  cache:
    disabled: true
  override-with-generic-response: false
  model-and-view-allowed: true
  default-consumes-media-type: application/json
  default-produces-media-type: application/json

ableAutoComplete: true

management:
  endpoints:
    web:
      exposure:
        include: "*"
        exclude: "env, beans"

server:
  tomcat:
    mbeanregistry:
      enabled: true

logging:
  level:
    org:
      hibernate:
        type:
          descriptor:
            sql: info

org:
  quartz:
    scheduler:
      instanceName: gaebaljip
      instanceId: AUTO
      rmi:
        export: false
        proxy: false
    threadPool:
      class: org.quartz.simpl.SimpleThreadPool
      threadCount: 5
    context:
      key:
        QuartzTopic: QuartzPorperties
    jobStore:
      class: org.quartz.impl.jdbcjobstore.JobStoreTX
      driverDelegateClass: org.quartz.impl.jdbcjobstore.StdJDBCDelegate
      tablePrefix: QRTZ_
      isClustered: true
      dataSource: gaebaljip
    dataSource:
      gaebaljip:
        provider: hikaricp
        driver: org.mariadb.jdbc.Driver
        URL: ${SPRING_DATASOURCE_URL}
        user: ${SPRING_DATASOURCE_USERNAME}
        password: ${SPRING_DATASOURCE_PASSWORD}
        maxConnections: 30
