version: '3'
services:
  mariadb:
    image: mariadb:10.6
    container_name: local-mariadb
    ports:
      - "3306:3306"
    environment:
      - RDS_DATABASE_ENDPOINT=${RDS_DATABASE_ENDPOINT}
      - RDS_PORT=${RDS_PORT}
      - RDS_DB_NAME=${RDS_DB_NAME}
      - RDS_DATABASE_USERNAME=${RDS_DATABASE_USERNAME}
      - RDS_DATABASE_PASSWORD=${RDS_DATABASE_PASSWORD}
    volumes:
      - ./db_data:/var/lib/mysql
