version: '3'
services:
  mariadb:
    image: mariadb:10.6
    container_name: local-mariadb
    ports:
      - "3306:3306"
    environment:
      - MARIADB_ROOT_PASSWORD=eatceed
      - MYSQL_DATABASE=gaebaljip
      - MYSQL_USER=gaebaljip-local
      - MYSQL_PASSWORD=gaebaljip-local
    volumes:
      - ./db_data:/var/lib/mysql