version: '3.8'

services:
  server:
    build: 
      context: ./server
    ports:
      - "8000:8000"
    env_file:
      - /home/ubuntu/.env
    depends_on:
      - food_classification

  food_classification:
    build:
      context: ./food_classification
    ports:
      - "8070:8070"
    env_file:
      - /home/ubuntu/.env
